version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/edm-server/config
      - ./src:/opt/edm-server/src
      - ./package.json:/opt/edm-server/package.json
      - ./yarn.lock:/opt/edm-server/yarn.lock
      - ./.env:/opt/edm-server/.env
      - ./public/uploads:/opt/edm-server/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - postgres

networks:
  strapi:
    name: Strapi
    driver: bridge