version: "3"
services:
  strapi:
    container_name: strapi
    build:
      context: /opt/edm-server/
      dockerfile: Dockerfile.production
    image: strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - /opt/edm-server/config:/opt/edm-server/config
      - /opt/edm-server/src:/opt/edm-server/src
      - /opt/edm-server/package.json:/opt/edm-server/package.json
      - /opt/edm-server/yarn.lock:/opt/edm-server/yarn.lock
      - /opt/edm-server/.env:/opt/edm-server/.env
      - /opt/edm-server/public/uploads:/opt/edm-server/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi


networks:
  strapi:
    name: Strapi
    driver: bridge